export enum ExpectedVendorOutcomeDomainModel {
    SUCCESS = 'SUCCESS',

    INCORRECT_FORM_ID = 'INCORRECT_FORM_ID',
    INCORRECT_FORM_TYPE = 'INCORRECT_FORM_TYPE',
    INCORRECT_SCHEMA = 'INCORRECT_SCHEMA',
    UNAUTHORIZED = 'UNAUTHORIZED'
}
